language: java
jdk:
  - openjdk8
services:
  - postgresql
before_install:
  - chmod +x mvnw
  - psql -c "CREATE DATABASE dbponto;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'portgres';" -U postgres
